from __future__ import annotations

from datetime import datetime
from io import StringIO
from typing import List

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqFeature import FeatureLocation, SeqFeature
from Bio.SeqRecord import SeqRecord

from logging_utils import get_conversation_logger
from .models import OutputInput, OutputOutput


class OutputAgent:
    """Converts constructed plasmid output to GenBank (.gbk) text."""

    def __init__(self) -> None:
        self._logger = get_conversation_logger()

    @staticmethod
    def _build_features(construct) -> List[SeqFeature]:
        features: List[SeqFeature] = []
        cursor = 0
        for el in construct.elements:
            start = cursor
            end = start + len(el.sequence)
            qualifiers = {
                "label": [el.requested_name],
                "note": [f"slot={el.slot}", f"source={el.source}"],
            }
            if el.from_web:
                qualifiers["note"].append("origin=web_fallback")
            features.append(
                SeqFeature(
                    location=FeatureLocation(start, end),
                    type=(el.element_type or "misc_feature").replace(" ", "_"),
                    qualifiers=qualifiers,
                )
            )
            cursor = end
        return features

    def run(self, inp: OutputInput) -> OutputOutput:
        self._logger.info("[OUTPUT] INPUT %s", inp.model_dump())
        record = SeqRecord(
            seq=Seq(inp.construct_output.construct_sequence),
            id=inp.name.replace(" ", "_"),
            name=inp.name.replace(" ", "_")[:16],
            description=f"Plasmid generated by OutputAgent ({inp.construct_output.template})",
        )
        record.annotations["molecule_type"] = "DNA"
        record.annotations["date"] = datetime.utcnow().strftime("%d-%b-%Y").upper()
        record.features = self._build_features(inp.construct_output)

        handle = StringIO()
        SeqIO.write(record, handle, "genbank")
        gbk_text = handle.getvalue()

        out = OutputOutput(
            gbk_text=gbk_text,
            file_name=f"{inp.name}.gbk",
            frontend_warnings=inp.construct_output.frontend_warnings,
        )
        self._logger.info("[OUTPUT] OUTPUT %s", out.model_dump(exclude={"gbk_text"}))
        return out
